In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('ONGC.csv')

In [ ]:
df

Date Symbol Series  Prev Close    Open   High     Low    Last  \
0     2000-01-03   ONGC     EQ      207.70  205.00  214.4  205.00  214.00   
1     2000-01-04   ONGC     EQ      213.45  201.50  209.7  201.00  209.00   
2     2000-01-05   ONGC     EQ      206.55  201.00  223.1  200.50  223.10   
3     2000-01-06   ONGC     EQ      223.10  234.00  234.9  217.60  217.60   
4     2000-01-07   ONGC     EQ      219.30  223.00  223.0  213.00  215.70   
...          ...    ...    ...         ...     ...    ...     ...     ...   
5301  2021-04-26   ONGC     EQ      102.40  105.25  105.7  102.50  102.80   
5302  2021-04-27   ONGC     EQ      102.80  102.80  104.0  102.80  103.30   
5303  2021-04-28   ONGC     EQ      103.20  103.75  104.4  103.30  104.05   
5304  2021-04-29   ONGC     EQ      103.90  104.90  105.9  103.55  104.30   
5305  2021-04-30   ONGC     EQ      104.05  104.15  112.7  103.30  108.20   

       Close    VWAP    Volume      Turnover    Trades  Deliverable Volume  \
0     213.45  209.91      9600  2.015090e+11       NaN                 NaN   
1     206.55  206.26     17900  3.692030e+11       NaN                 NaN   
2     223.10  215.46     27000  5.817490e+11       NaN                 NaN   
3     219.30  223.42     35600  7.953680e+11       NaN                 NaN   
4     215.75  215.19     11400  2.453145e+11       NaN                 NaN   
...      ...     ...       ...           ...       ...                 ...   
5301  102.80  103.86  11797791  1.225355e+14   63132.0           3024740.0   
5302  103.20  103.42   8886250  9.189768e+13   46923.0           3802836.0   
5303  103.90  103.90   6887787  7.156081e+13   33659.0           2533669.0   
5304  104.05  104.39  14990087  1.564876e+14   54416.0           4613745.0   
5305  108.15  109.79  81358264  8.932632e+14  248419.0          15306987.0   

      %Deliverble  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
5301       0.2564  
5302       0.4279  
5303       0.3678  
5304       0.3078  
5305       0.1881  

[5306 rows x 15 columns]

In [ ]:
df.isnull().sum()

Date                     0
Symbol                   0
Series                   0
Prev Close               0
Open                     0
High                     0
Low                      0
Last                     0
Close                    0
VWAP                     0
Volume                   0
Turnover                 0
Trades                2850
Deliverable Volume     509
%Deliverble            509
dtype: int64

In [ ]:
df.dropna(axis =1, inplace =True)
df

Date Symbol Series  Prev Close    Open   High     Low    Last  \
0     2000-01-03   ONGC     EQ      207.70  205.00  214.4  205.00  214.00   
1     2000-01-04   ONGC     EQ      213.45  201.50  209.7  201.00  209.00   
2     2000-01-05   ONGC     EQ      206.55  201.00  223.1  200.50  223.10   
3     2000-01-06   ONGC     EQ      223.10  234.00  234.9  217.60  217.60   
4     2000-01-07   ONGC     EQ      219.30  223.00  223.0  213.00  215.70   
...          ...    ...    ...         ...     ...    ...     ...     ...   
5301  2021-04-26   ONGC     EQ      102.40  105.25  105.7  102.50  102.80   
5302  2021-04-27   ONGC     EQ      102.80  102.80  104.0  102.80  103.30   
5303  2021-04-28   ONGC     EQ      103.20  103.75  104.4  103.30  104.05   
5304  2021-04-29   ONGC     EQ      103.90  104.90  105.9  103.55  104.30   
5305  2021-04-30   ONGC     EQ      104.05  104.15  112.7  103.30  108.20   

       Close    VWAP    Volume      Turnover  
0     213.45  209.91      9600  2.015090e+11  
1     206.55  206.26     17900  3.692030e+11  
2     223.10  215.46     27000  5.817490e+11  
3     219.30  223.42     35600  7.953680e+11  
4     215.75  215.19     11400  2.453145e+11  
...      ...     ...       ...           ...  
5301  102.80  103.86  11797791  1.225355e+14  
5302  103.20  103.42   8886250  9.189768e+13  
5303  103.90  103.90   6887787  7.156081e+13  
5304  104.05  104.39  14990087  1.564876e+14  
5305  108.15  109.79  81358264  8.932632e+14  

[5306 rows x 12 columns]

In [ ]:
df.drop('Date', inplace = True, axis =1)
df

Symbol Series  Prev Close    Open   High     Low    Last   Close    VWAP  \
0      ONGC     EQ      207.70  205.00  214.4  205.00  214.00  213.45  209.91   
1      ONGC     EQ      213.45  201.50  209.7  201.00  209.00  206.55  206.26   
2      ONGC     EQ      206.55  201.00  223.1  200.50  223.10  223.10  215.46   
3      ONGC     EQ      223.10  234.00  234.9  217.60  217.60  219.30  223.42   
4      ONGC     EQ      219.30  223.00  223.0  213.00  215.70  215.75  215.19   
...     ...    ...         ...     ...    ...     ...     ...     ...     ...   
5301   ONGC     EQ      102.40  105.25  105.7  102.50  102.80  102.80  103.86   
5302   ONGC     EQ      102.80  102.80  104.0  102.80  103.30  103.20  103.42   
5303   ONGC     EQ      103.20  103.75  104.4  103.30  104.05  103.90  103.90   
5304   ONGC     EQ      103.90  104.90  105.9  103.55  104.30  104.05  104.39   
5305   ONGC     EQ      104.05  104.15  112.7  103.30  108.20  108.15  109.79   

        Volume      Turnover  
0         9600  2.015090e+11  
1        17900  3.692030e+11  
2        27000  5.817490e+11  
3        35600  7.953680e+11  
4        11400  2.453145e+11  
...        ...           ...  
5301  11797791  1.225355e+14  
5302   8886250  9.189768e+13  
5303   6887787  7.156081e+13  
5304  14990087  1.564876e+14  
5305  81358264  8.932632e+14  

[5306 rows x 11 columns]

In [ ]:
df.drop('Symbol', inplace = True, axis =1)
df.drop('Series', inplace = True, axis =1)
df

Prev Close    Open   High     Low    Last   Close    VWAP    Volume  \
0         207.70  205.00  214.4  205.00  214.00  213.45  209.91      9600   
1         213.45  201.50  209.7  201.00  209.00  206.55  206.26     17900   
2         206.55  201.00  223.1  200.50  223.10  223.10  215.46     27000   
3         223.10  234.00  234.9  217.60  217.60  219.30  223.42     35600   
4         219.30  223.00  223.0  213.00  215.70  215.75  215.19     11400   
...          ...     ...    ...     ...     ...     ...     ...       ...   
5301      102.40  105.25  105.7  102.50  102.80  102.80  103.86  11797791   
5302      102.80  102.80  104.0  102.80  103.30  103.20  103.42   8886250   
5303      103.20  103.75  104.4  103.30  104.05  103.90  103.90   6887787   
5304      103.90  104.90  105.9  103.55  104.30  104.05  104.39  14990087   
5305      104.05  104.15  112.7  103.30  108.20  108.15  109.79  81358264   

          Turnover  
0     2.015090e+11  
1     3.692030e+11  
2     5.817490e+11  
3     7.953680e+11  
4     2.453145e+11  
...            ...  
5301  1.225355e+14  
5302  9.189768e+13  
5303  7.156081e+13  
5304  1.564876e+14  
5305  8.932632e+14  

[5306 rows x 9 columns]

In [ ]:
df.corr()

Prev Close      Open      High       Low      Last     Close  \
Prev Close    1.000000  0.999137  0.998944  0.998737  0.998686  0.998710   
Open          0.999137  1.000000  0.999590  0.999419  0.999236  0.999266   
High          0.998944  0.999590  1.000000  0.999259  0.999635  0.999662   
Low           0.998737  0.999419  0.999259  1.000000  0.999561  0.999588   
Last          0.998686  0.999236  0.999635  0.999561  1.000000  0.999974   
Close         0.998710  0.999266  0.999662  0.999588  0.999974  1.000000   
VWAP          0.998946  0.999528  0.999800  0.999684  0.999865  0.999901   
Volume       -0.314333 -0.314461 -0.313025 -0.315354 -0.314191 -0.314109   
Turnover      0.131939  0.131807  0.137109  0.127451  0.132536  0.132519   

                VWAP    Volume  Turnover  
Prev Close  0.998946 -0.314333  0.131939  
Open        0.999528 -0.314461  0.131807  
High        0.999800 -0.313025  0.137109  
Low         0.999684 -0.315354  0.127451  
Last        0.999865 -0.314191  0.132536  
Close       0.999901 -0.314109  0.132519  
VWAP        1.000000 -0.314151  0.132823  
Volume     -0.314151  1.000000  0.640352  
Turnover    0.132823  0.640352  1.000000

# **SIMPLE LINEAR REGRESSION**

In [ ]:
X = df.iloc[:, -2:-1].values
X

array([[    9600],
       [   17900],
       [   27000],
       ...,
       [ 6887787],
       [14990087],
       [81358264]])

In [ ]:
Y = df.iloc[:, -1].values
Y

array([2.01509000e+11, 3.69203000e+11, 5.81749000e+11, ...,
       7.15608091e+13, 1.56487556e+14, 8.93263184e+14])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor = regressor.fit(X_train, Y_train)

In [ ]:
Y_pred = regressor.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.514197088906144

MULTIPLE LINEAR REGRESSION

In [ ]:
df.drop('Low', inplace = True, axis =1)
df

Prev Close    Open   High    Last   Close    VWAP    Volume  \
0         207.70  205.00  214.4  214.00  213.45  209.91      9600   
1         213.45  201.50  209.7  209.00  206.55  206.26     17900   
2         206.55  201.00  223.1  223.10  223.10  215.46     27000   
3         223.10  234.00  234.9  217.60  219.30  223.42     35600   
4         219.30  223.00  223.0  215.70  215.75  215.19     11400   
...          ...     ...    ...     ...     ...     ...       ...   
5301      102.40  105.25  105.7  102.80  102.80  103.86  11797791   
5302      102.80  102.80  104.0  103.30  103.20  103.42   8886250   
5303      103.20  103.75  104.4  104.05  103.90  103.90   6887787   
5304      103.90  104.90  105.9  104.30  104.05  104.39  14990087   
5305      104.05  104.15  112.7  108.20  108.15  109.79  81358264   

          Turnover  
0     2.015090e+11  
1     3.692030e+11  
2     5.817490e+11  
3     7.953680e+11  
4     2.453145e+11  
...            ...  
5301  1.225355e+14  
5302  9.189768e+13  
5303  7.156081e+13  
5304  1.564876e+14  
5305  8.932632e+14  

[5306 rows x 8 columns]

In [ ]:
X = df.iloc[:,:-1].values
X

array([[2.0770000e+02, 2.0500000e+02, 2.1440000e+02, ..., 2.1345000e+02,
        2.0991000e+02, 9.6000000e+03],
       [2.1345000e+02, 2.0150000e+02, 2.0970000e+02, ..., 2.0655000e+02,
        2.0626000e+02, 1.7900000e+04],
       [2.0655000e+02, 2.0100000e+02, 2.2310000e+02, ..., 2.2310000e+02,
        2.1546000e+02, 2.7000000e+04],
       ...,
       [1.0320000e+02, 1.0375000e+02, 1.0440000e+02, ..., 1.0390000e+02,
        1.0390000e+02, 6.8877870e+06],
       [1.0390000e+02, 1.0490000e+02, 1.0590000e+02, ..., 1.0405000e+02,
        1.0439000e+02, 1.4990087e+07],
       [1.0405000e+02, 1.0415000e+02, 1.1270000e+02, ..., 1.0815000e+02,
        1.0979000e+02, 8.1358264e+07]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([2.01509000e+11, 3.69203000e+11, 5.81749000e+11, ...,
       7.15608091e+13, 1.56487556e+14, 8.93263184e+14])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor = regressor.fit(X_train, Y_train)

In [ ]:
Y_pred = regressor.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.6603087407675701

# **SUPPORT VECTOR REGRESSOR**

In [ ]:
X = df.iloc[:,:-1].values
X

array([[2.0770000e+02, 2.0500000e+02, 2.1440000e+02, ..., 2.1345000e+02,
        2.0991000e+02, 9.6000000e+03],
       [2.1345000e+02, 2.0150000e+02, 2.0970000e+02, ..., 2.0655000e+02,
        2.0626000e+02, 1.7900000e+04],
       [2.0655000e+02, 2.0100000e+02, 2.2310000e+02, ..., 2.2310000e+02,
        2.1546000e+02, 2.7000000e+04],
       ...,
       [1.0320000e+02, 1.0375000e+02, 1.0440000e+02, ..., 1.0390000e+02,
        1.0390000e+02, 6.8877870e+06],
       [1.0390000e+02, 1.0490000e+02, 1.0590000e+02, ..., 1.0405000e+02,
        1.0439000e+02, 1.4990087e+07],
       [1.0405000e+02, 1.0415000e+02, 1.1270000e+02, ..., 1.0815000e+02,
        1.0979000e+02, 8.1358264e+07]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([2.01509000e+11, 3.69203000e+11, 5.81749000e+11, ...,
       7.15608091e+13, 1.56487556e+14, 8.93263184e+14])

In [ ]:
X.shape

(5306, 7)

In [ ]:
Y.shape

(5306,)

In [ ]:
Y = Y.reshape(len(Y),1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X = sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor = regressor.fit(X, Y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test,Y_pred)

0.8830620406020278

# **DECISION TREE**

In [ ]:
X = df.iloc[:,:-1].values
X

array([[2.0770000e+02, 2.0500000e+02, 2.1440000e+02, ..., 2.1345000e+02,
        2.0991000e+02, 9.6000000e+03],
       [2.1345000e+02, 2.0150000e+02, 2.0970000e+02, ..., 2.0655000e+02,
        2.0626000e+02, 1.7900000e+04],
       [2.0655000e+02, 2.0100000e+02, 2.2310000e+02, ..., 2.2310000e+02,
        2.1546000e+02, 2.7000000e+04],
       ...,
       [1.0320000e+02, 1.0375000e+02, 1.0440000e+02, ..., 1.0390000e+02,
        1.0390000e+02, 6.8877870e+06],
       [1.0390000e+02, 1.0490000e+02, 1.0590000e+02, ..., 1.0405000e+02,
        1.0439000e+02, 1.4990087e+07],
       [1.0405000e+02, 1.0415000e+02, 1.1270000e+02, ..., 1.0815000e+02,
        1.0979000e+02, 8.1358264e+07]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([2.01509000e+11, 3.69203000e+11, 5.81749000e+11, ...,
       7.15608091e+13, 1.56487556e+14, 8.93263184e+14])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
Y_pred = regressor.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.9223826292261156

# **RANDOM FOREST**

In [ ]:
X = df.iloc[:,:-1].values
X

array([[2.0770000e+02, 2.0500000e+02, 2.1440000e+02, ..., 2.1345000e+02,
        2.0991000e+02, 9.6000000e+03],
       [2.1345000e+02, 2.0150000e+02, 2.0970000e+02, ..., 2.0655000e+02,
        2.0626000e+02, 1.7900000e+04],
       [2.0655000e+02, 2.0100000e+02, 2.2310000e+02, ..., 2.2310000e+02,
        2.1546000e+02, 2.7000000e+04],
       ...,
       [1.0320000e+02, 1.0375000e+02, 1.0440000e+02, ..., 1.0390000e+02,
        1.0390000e+02, 6.8877870e+06],
       [1.0390000e+02, 1.0490000e+02, 1.0590000e+02, ..., 1.0405000e+02,
        1.0439000e+02, 1.4990087e+07],
       [1.0405000e+02, 1.0415000e+02, 1.1270000e+02, ..., 1.0815000e+02,
        1.0979000e+02, 8.1358264e+07]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([2.01509000e+11, 3.69203000e+11, 5.81749000e+11, ...,
       7.15608091e+13, 1.56487556e+14, 8.93263184e+14])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 12, random_state = 0)
regressor.fit(X_train,Y_train)

RandomForestRegressor(n_estimators=12, random_state=0)

In [ ]:
#accuracy
from sklearn.metrics import r2_score
r2_score(Y, regressor.predict(X))

0.9708290064915961

# **POLYNOMIAL REGRESSION**

In [ ]:
X = df.iloc[:,:-1].values
X

array([[2.0770000e+02, 2.0500000e+02, 2.1440000e+02, ..., 2.1345000e+02,
        2.0991000e+02, 9.6000000e+03],
       [2.1345000e+02, 2.0150000e+02, 2.0970000e+02, ..., 2.0655000e+02,
        2.0626000e+02, 1.7900000e+04],
       [2.0655000e+02, 2.0100000e+02, 2.2310000e+02, ..., 2.2310000e+02,
        2.1546000e+02, 2.7000000e+04],
       ...,
       [1.0320000e+02, 1.0375000e+02, 1.0440000e+02, ..., 1.0390000e+02,
        1.0390000e+02, 6.8877870e+06],
       [1.0390000e+02, 1.0490000e+02, 1.0590000e+02, ..., 1.0405000e+02,
        1.0439000e+02, 1.4990087e+07],
       [1.0405000e+02, 1.0415000e+02, 1.1270000e+02, ..., 1.0815000e+02,
        1.0979000e+02, 8.1358264e+07]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([2.01509000e+11, 3.69203000e+11, 5.81749000e+11, ...,
       7.15608091e+13, 1.56487556e+14, 8.93263184e+14])

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,Y)

LinearRegression()

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 3)
X_poly = poly_reg.fit_transform(X)
X

array([[-0.73597402, -0.74397131, -0.72827885, ..., -0.72096549,
        -0.73070793, -0.51665712],
       [-0.72104459, -0.75304682, -0.74025619, ..., -0.73888005,
        -0.74017761, -0.51572848],
       [-0.7389599 , -0.75434333, -0.70610802, ..., -0.69591107,
        -0.71630882, -0.51471033],
       ...,
       [-1.00730017, -1.00651297, -1.00859962, ..., -1.00539158,
        -1.00574385,  0.25290518],
       [-1.00548267, -1.00353101, -1.00477706, ..., -1.00500214,
        -1.00447258,  1.15942673],
       [-1.00509321, -1.00547576, -0.98744814, ..., -0.99435725,
        -0.99046264,  8.58499505]])

In [ ]:
X_poly

array([[ 1.00000000e+00, -7.35974015e-01, -7.43971310e-01, ...,
        -2.75860843e-01, -1.95051216e-01, -1.37913654e-01],
       [ 1.00000000e+00, -7.21044586e-01, -7.53046824e-01, ...,
        -2.82548500e-01, -1.96869383e-01, -1.37171331e-01],
       [ 1.00000000e+00, -7.38959901e-01, -7.54343326e-01, ...,
        -2.64097010e-01, -1.89769352e-01, -1.36360525e-01],
       ...,
       [ 1.00000000e+00, -1.00730017e+00, -1.00651297e+00, ...,
         2.55818828e-01, -6.43284149e-02,  1.61760766e-02],
       [ 1.00000000e+00, -1.00548267e+00, -1.00353101e+00, ...,
         1.16982118e+00, -1.35028269e+00,  1.55858296e+00],
       [ 1.00000000e+00, -1.00509321e+00, -1.00547576e+00, ...,
         8.42201952e+00, -7.29992159e+01,  6.32732507e+02]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_poly, Y, test_size = 0.2, random_state = 0)

In [ ]:
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly, Y)

LinearRegression()

In [ ]:
lin_reg2.fit(X_train, Y_train)

LinearRegression()

In [ ]:
Y_pred = lin_reg2.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(Y_test, Y_pred))

0.9999998624602191
